project:
  type: website
  output-dir: "../docs"

website:
  navbar:
    background: primary
    title: "SDS 410: SDS Capstone"
    right:
      - text: "Syllabus"
        href: index.html
      - text: "Self-Assessment"
        href: grading_contract.html
      - text: "Schedule"
        href: schedule.html

format:
  html:
    theme: flatly
    css: "css/custom.css"
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    highlight: tango
    lib_dir: libs



