---
title: "Mid-Semester Assessment"
author: "Lindsay Poirier"
format: html
editor: visual
---

## Mid-Semester Assessment

::: callout-tip
## Why am I asking you to do this?

- This assignment seeks to provide you with an opportunity to reflect on your personal growth in the course and more deeply engage with considerations on where you'd like to improve. Swaths of research indicate that learning improves when students are provided with explicit opportunities for this kind of reflection. 
- The ability to critically evaluate your own performance is an important skill that you will engage no matter where your career takes you post-graduation.
- This assignment is designed to help strengthen your general review practices, by asking you to provide evidence and reasoning for a particular evaluation. 
- This assignment is meant to give you more agency over how you are assessed in this course. 
:::

Following Spring Break, you should submit a 700-800-word mid-semester assessment of your work, grading yourself along each of the course's [seven dimensions](grading_contract.html). For each dimension, you will develop an argument for why you should receive a particular grade (A, B, C, D, etc), drawing evidence from your log to support your argument. Your assessment should conclude by reflecting on areas for improvement in the second half of the semester.

::: callout-tip
## Keep in mind!

Your grade in this course is about growth. Your justifications should **describe your growth along each dimension**, not just how you met certain criteria in the dimension. This means that when you are identifying examples to talk about in your write-up, your arguments should explain *how you developed new skills, new habits of working, or new ways of thinking through engagement in our course*. It’s one thing to say: “I met the professionalism dimension by submitting materials on time and showing up to each meeting”, but that doesn’t tell me that you’ve learned anything in the course. Use this opportunity to engage deeper reflection on what new skills you've learned.
:::

You should submit this assignment to your Github portfolio repository as a .qmd in the `reflections` folder. Please be sure to have separate headings for each of the course's dimensions, and to clearly list the grade you would give yourself for each.

I want you to think of this assignment as an opportunity to generate material that you might reference when preparing job or graduate school materials. In cover letters and interviews, you may be expected to recall and detail specific instances where you demonstrated professionalism, where you learned to manage conflict in a collaboration, or where you overcame a challenge in project management. I'm asking you to provide specific examples in support of a grade, not only as proof of why you deserve that grade, but also because it will give you practice in effective self-advocating.
