---
title: "Presentation Tips"
format: html
editor: visual
---

## Introduction

This document lists a few important criteria you might consider when evaluating your mid-semester presentations and preparing for your final presentations. 

## Body Language/ Movement

1.  Characterize the speaker's posture. Is the speaker slouching? Poised? Stiff or rigid? Inviting? Relaxed? Did you find the speaker's posture distracting? Would you have noticed it if you weren't looking for it?

2.  Characterize the speaker's eye contact with the audience. Did the speaker seem to connect with people throughout the audience? Did you notice moments when the speaker was looking down? If so, did you feel like the speaker lost a connection with the audience in these moments?

## Oration

1.  Characterize the pace of the presenter's speech. Did you have a hard time keeping up with the speaker? When did the speaker speed up, and when did the speaker slow down? How effective was the pacing of speech in delivering the presentation?

2.  How much vocal variety was in the speaker's voice? Was the presenter monotonous or droning in their speech? When did the pitch of their voice rise and drop? How effective was the variation in their vocals in keeping the audience engaged?

3.  How well did the speaker articulate words? Were the words and sentences of the presentation crisp and easy to discern? Did you have trouble making out any of the speaker's words? Did the speaker appear to be mumbling at certain points? What were some of the speaker's filler words (um's, like's, you know's)? Were they distracting?

## Composition

1.  When did the presenter pause throughout the presentation? Were pauses used as dramatic effect -- allowing a compelling statement to sink in? Were they used for the speaker to catch their breath? Did the speaker stop to take a sip of water? How effectively were pauses used throughout the presentation?

## Content and Organization

1.  At what point in the presentation were you able to grasp the presenter's thesis or main argument? If it was later in the presentation, did you feel confused up until that point? If it was earlier, did you feel the presentation lacked suspense? Did you find the timing of the delivery of the thesis effective?
2.  What strategies did the presenter use to make difficult concepts more accessible? Did the presenter define key terms, and if so, were these definitions clear and easy to comprehend? Did the presenter provide examples, and if so, to what extent did these examples help you grasp the meaning of the concept?

## **Visuals/Graphics**

1.  How did the presenter use visuals or graphics throughout the presentation? To what extent did the visuals help to support the presenter's argument? Were you able to readily make sense of what you were looking at? Were you able to pay attention to what the speaker was saying as you viewed the graphics? What about the graphics (their size, their color, their color variation, their complexity) played a role in your ability to stay connected with the speaker while viewing the graphic?

2.  Did the presenter have any text on their presentation slides? If so, how dense was the text? Were you able to read the text and still pay attention to what the speaker was saying? What about the text (its size, its color, its color variation, its complexity) played a role in your ability to stay connected with the speaker while viewing the text? To what extent did the text help to support the presenter's argument?
