---
title: "Reading Discussions"
---

Reading discussions will be approximately 40 minutes.

Ahead of class, the assigned team should develop 4-5 discussion questions (one per team member) related to the chapter's arguments for discussion during class. Questions may:

* Reflect on the chapter's main arguments
* Clarify or unpack a concept developed in the chapter
* Connect the chapter's arguments to current events
* Prompt us to think about how the arguments impact our work/lives

Each team member will be responsible for facilitating small group discussions on one of the questions the team developed.
In class, we will split into 4-5 groups for 10-minute small group discussions - one group per question. Then we will switch up the groups and repeat this process again.

Then we will come back together for the last 20 minutes; each team member will briefly report on what was discussed in the two small group discussions they facilitated, and finally we will open the room for class discussion (led by me or Swaha).


